# Generated by Django 5.1.7 on 2025-03-21 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatheralert_recommendation_weatheralert_severity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_settings',
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_rain', models.BooleanField(default=False)),
                ('notify_low_temp', models.BooleanField(default=False)),
                ('notify_high_temp', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
